### ISSUE TITLE
Missing DLLs on Windows via pip install

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OMSimulator#1027]
### Description

Only OMSimulator.dll and omtlmsimulator.dll are installed in:
python\lib\site-packages\OMSimulator\
Is missing:
libxml2.dll, pthreadVC2.dll, boost_filesystem-vc141-mt-1_64.dll, boost_system-vc141-mt-1_64.dll

### Steps to reproduce the behavior

/path/to/windows/python -m pip install OMSimulator
```
python -m pip install OMSimulator --upgrade
Collecting OMSimulator
  Downloading OMSimulator-2.1.1.post59.tar.gz (3.0 kB)
Requirement already satisfied: requests in e:\bin\py64\lib\site-packages (from OMSimulator) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\bin\py64\lib\site-packages (from requests->OMSimulator) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in e:\bin\py64\lib\site-packages (from requests->OMSimulator) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in e:\bin\py64\lib\site-packages (from requests->OMSimulator) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in e:\bin\py64\lib\site-packages (from requests->OMSimulator) (4.0.0)
Using legacy 'setup.py install' for OMSimulator, since package 'wheel' is not installed.
Installing collected packages: OMSimulator
    Running setup.py install for OMSimulator: started
    Running setup.py install for OMSimulator: finished with status 'done'
Successfully installed OMSimulator-2.1.1.post59
WARNING: You are using pip version 21.0.1; however, version 21.1.1 is available.
```

Run any python script using OMSimulator:
```batch
python.exe pem.py
Traceback (most recent call last):
  File "pem.py", line 3, in <module>
    import OMSimulator as oms
  File "E:\bin\py64\lib\site-packages\OMSimulator\__init__.py", line 17, in <module>
    Scope._init()
  File "E:\bin\py64\lib\site-packages\OMSimulator\Scope.py", line 5, in _init
    _capi = capi()
  File "E:\bin\py64\lib\site-packages\OMSimulator\capi.py", line 11, in __init__
    self.obj=ctypes.CDLL(omslib)
  File "E:\bin\py64\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\bin\py64\lib\site-packages\OMSimulator\OMSimulator.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

Finding out which dll is missing:
```batch
ntldd -R /e/bin/py64/Lib/site-packages/OMSimulator/OMSimulator.dll | grep -v "ext-ms" | grep -v WINDOWS
        omtlmsimulator.dll => E:\bin\py64\Lib\site-packages\OMSimulator\omtlmsimulator.dll (0x0000000000f50000)
         libxml2.dll => not found
         pthreadVC2.dll => not found
        boost_filesystem-vc141-mt-1_64.dll => not found
        boost_system-vc141-mt-1_64.dll => not found
```

### Expected behavior

Running with no issue ...

### Version and OS

Window 10 64bit

**Comment by adrpo** [comment]
I managed to get the dlls from an older version, no problem for me to run the stuff. I just think the pip stuff should contain everything needed.

**Comment by arun3688** [comment]
@adrpo the pip `setup.py` currently looks for the dlls in only `lib/OMSimulator` folder and that is the problem, and I guess now only the dlls starting with  "OMSimulatorXXX.dll" is copied to "lib/OMSimuator" , This commit https://github.com/OpenModelica/OMSimulator/commit/ac94aaf7fbf3ba4b081f21f91367cbd6bf4e9bde does that and it fails to copy the boost and other dependant dlls needed for windows

**Comment by arun3688** [comment]
This issue is fixed with this commit https://github.com/OpenModelica/OMSimulator/commit/9b56534e274d0a3e28863b92e79443ad86f151d4
