### ISSUE TITLE
Recommended way to install OMSimulator on Windows

### ISSUE THREAD

**Issue by kosmylo** [OpenModelica/OMSimulator#1077]
I tried to install OMSimulator through anaconda, but I got the following error:

```
 Downloading OMSimulator-2.0.0.post267.tar.gz (3.0 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\kosmy\anaconda3\envs\OMSimulator\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kosmy\\AppData\\Local\\Temp\\pip-install-ybr81eo5\\omsimulator_cdcf5e8005404a03bbce1503cfc3251e\\setup.py'"'"'; __file__='"'"'C:\\Users\\kosmy\\AppData\\Local\\Temp\\pip-install-ybr81eo5\\omsimulator_cdcf5e8005404a03bbce1503cfc3251e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\kosmy\AppData\Local\Temp\pip-pip-egg-info-6nb5ogqr'
         cwd: C:\Users\kosmy\AppData\Local\Temp\pip-install-ybr81eo5\omsimulator_cdcf5e8005404a03bbce1503cfc3251e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\kosmy\AppData\Local\Temp\pip-install-ybr81eo5\omsimulator_cdcf5e8005404a03bbce1503cfc3251e\setup.py", line 41, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/29/dd/50f56f0ddbfaf6573834473a227c27d741e8611dcc15ce42ea7bf93189bd/OMSimulator-2.0.0.post267.tar.gz#sha256=f50b1b489bf8f138f33a9e49f86e030461b7a25152dbab7aab3dd04d05c2dd36 (from https://pypi.org/simple/omsimulator/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement omsimulator (from versions: 2.0.0.post267, 2.0.0.post276, 2.0.0.post285, 2.0.0.post286, 2.1.0, 2.1.1, 2.1.1.post1, 2.1.1.post15, 2.1.1.post50, 2.1.1.post52, 2.1.1.post55, 2.1.1.post59, 2.1.1.post73, 2.1.1.post108, 2.1.1.post109)
ERROR: No matching distribution found for omsimulator
```
Is there a recommended way to install it on windows?

**Comment by lochel** [comment]
You should first install 'requests' and then OMSimulator. @arun3688 I guess we should include it in the setup as dependency.

**Comment by arun3688** [comment]
@lochel , OMSimulator does not have any dependencies, but the `setup.py` file is dependant on `requests` package to fetch the artifacts, So we need to check for `requests` package installed or not when running the `setup.py` and install it if not found, otherwise the users have to install the `requests` package by themselves

**Comment by lochel** [comment]
@kosmylo is the issue solved for you?

**Comment by kosmylo** [comment]
> @kosmylo is the issue solved for you?

Yes, I was able to install it successfully.
