### ISSUE TITLE
Segfault on Linux Mint 19.3

### ISSUE THREAD

**Issue by superlou** [OpenModelica/OMSimulator#767]
### Description

When trying to run OMSimulator with an fmu file ([ShipsWiringSim.fmu.zip](https://github.com/OpenModelica/OMSimulator/files/5009424/ShipsWiringSim.fmu.zip), remove zip extension), the executable segfaults.

I have verified that the simulation works normally on the current Windows build. I have the same behavior with the current Linux build as well as build from the current master.

### Steps to reproduce the behavior

`./OMSimulator ShipsWiringSim.fmu`

### Expected behavior

System instantiates, initializes, and simulates.

### Screenshots

```
./OMSimulator ~/workspace/cirship/modelica/ShipsWiringSim.fmu --version
OMSimulator v2.1.0-dev-177-g0d19b0d-linux
info:    Set temp directory to    "/home/lsimons/workspace/OMSimulator/build/linux/src/OMSimulator"
info:    Set working directory to "/home/lsimons/workspace/OMSimulator/build/linux/src/OMSimulator"
info:    Set working directory to "/home/lsimons/workspace/OMSimulator/build/linux/src/OMSimulator"
info:    New model "model" with corresponding temp directory "/home/lsimons/workspace/OMSimulator/build/linux/src/OMSimulator/model-obpasjvw"
Segmentation fault (core dumped)
```

### Version and OS

- Version: v2.1.0-dev-177-g0d19b0d-linux (as well as current Linux build)
- OS: Linux Mint 19.3
- CPU: AMD Phenom II x6

I tried running through GDB and got a little more information:

```
Program received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x000055555572ec69 in oms::Connector::Connector(oms_causality_enu_t, oms_signal_type_enu_t, oms::ComRef const&) ()
#2  0x000055555571c8a8 in oms::ComponentFMUME::initializeDependencyGraph_initialUnknowns() ()
#3  0x00005555557228fd in oms::ComponentFMUME::NewComponent(oms::ComRef const&, oms::System*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#4  0x00005555556a7cc6 in oms::System::addSubModel(oms::ComRef const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x00005555556797aa in oms_addSubModel ()
#6  0x0000555555686492 in oms_RunFile ()
#7  0x000055555573da95 in oms::Flags::SetCommandLineOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x000055555566d203 in oms_setCommandLineOption ()
#9  0x0000555555665d6a in main ()
```

The Phenom II processor should support the SSE2 instruction set. Is there a way to get more information? Is it possible to configure `make` to build with debug symbols?

Edit: I think I was able to build with debug symbols by following [instructions](https://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake). The stack trace is:

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
info:    Set temp directory to    "/home/lsimons/workspace/OMSimulator/Debug/src/OMSimulator"
info:    Set working directory to "/home/lsimons/workspace/OMSimulator/Debug/src/OMSimulator"
info:    Set working directory to "/home/lsimons/workspace/OMSimulator/Debug/src/OMSimulator"
info:    New model "model" with corresponding temp directory "/home/lsimons/workspace/OMSimulator/Debug/src/OMSimulator/model-i3dj5ajm"

Program received signal SIGSEGV, Segmentation fault.
0x00005555557a29b1 in std::char_traits<char>::length (
    __s=0x5265756c61762020 <error: Cannot access memory at address 0x5265756c61762020>) at /usr/include/c++/7/bits/char_traits.h:320
320		return __builtin_strlen(__s);
(gdb) bt
#0  0x00005555557a29b1 in std::char_traits<char>::length (
    __s=0x5265756c61762020 <error: Cannot access memory at address 0x5265756c61762020>) at /usr/include/c++/7/bits/char_traits.h:320
#1  0x00005555557c8dc1 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fffffffd1e0, 
    __s=0x5265756c61762020 <error: Cannot access memory at address 0x5265756c61762020>, __a=...) at /usr/include/c++/7/bits/basic_string.h:511
#2  0x00005555557c359e in oms::ComRef::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (this=0x555556019810)
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/ComRef.h:66
#3  0x000055555589ad74 in oms::Variable::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (this=0x555556019810)
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/Variable.h:76
#4  0x00005555558a3393 in oms::ComponentFMUME::initializeDependencyGraph_initialUnknowns (this=0x555556010fb0)
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/ComponentFMUME.cpp:393
#5  0x00005555558a1672 in oms::ComponentFMUME::NewComponent (cref=..., 
    parentSystem=0x5555560107f0, 
    fmuPath="/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu")
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/ComponentFMUME.cpp:242
#6  0x00005555557e14aa in oms::System::addSubModel (this=0x5555560107f0, 
    ., path="/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu") at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/System.cpp:288
#7  0x00005555557b4516 in oms_addSubModel (cref=0x7fffffffd970 "model.root.fmu", 
    fmuPath=0x55555600d9c0 "/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu")
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:807
#8  0x00005555557b7c01 in oms_RunFile (filename_=0x55555600da10 "/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu")
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:1057
#9  0x00005555558c19f1 in oms::Flags::SetCommandLineOption (cmd="/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu")
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/Flags.cpp:166
#10 0x00005555557acb6c in oms_setCommandLineOption (cmd=0x555555ff4d00 "/home/lsimons/workspace/cirship/modelica/ShipsWiringSim.fmu")
    at /home/lsimons/workspace/OMSimulator/src/OMSimulatorLib/OMSimulator.cpp:373
#11 0x00005555557a28fa in main (argc=2, argv=0x7fffffffdd68) at /home/lsimons/workspace/OMSimulator/src/OMSimulator/main.cpp:45

```

**Comment by superlou** [comment]
It looks like it's something with the FMU I was using to test, because I can make a simpler FMU run without segfaulting:
[SimpleElectrical.fmu.zip](https://github.com/OpenModelica/OMSimulator/files/5012738/SimpleElectrical.fmu.zip).
